- hosts: azure
  name: Create resources for VMs
  tasks:
    - name: Create the reseource group
      azure_rm_resourcegroup:
        name: ansible-rhel-rg
        location: eastus
    
    - name: Create the virtual subnet
      azure_rm_subnet:
        name: ansible-rhel-subnet
        resource_group: ansible-rhel-rg
        virtual_network_name: ansible-rhel-vnet
        address_prefix_cidr: "10.1.0.0/24"
    
    - name: Create the virtual subnet
      azure_rm_subnet:
        name: ansible-rhel-subnet
        resource_group: ansible-rhel-rg
        virtual_network_name: ansible-rhel-vnet
        address_prefix_cidr: "10.1.0.0/24"
    
    - name: Create public ip address
      azure_rm_publicipaddress:
        name: ansible-rhel-ip
        resource_group: ansible-rhel-rg
        allocation-method: Static
      register: ansible_rhel_ip
    
    - name: Create the security group to allow ssh connection
      azure_rm_securitygroup:
        name: ansible-rhel-sg
        resource_group: ansible-rhel-rg
        purge_rues: yes
        rules:
          - name: 'AllowSSH'
            protocol: tcp
            source_address_prefix:
              - '0.0.0.0/0'
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound
    
    - name: Create the virtual network interface card
      azure_rm_networkinterface:
        name: ansible-rhel-nic
        resource_group: ansible-rhel-rg
        virtual_network: ansible-rhel-vnet
        subnet: ansible-rhel-subnet
        public_ip_name: ansible-rhel-ip
        security_group: ansible-rhel-sg
    
    - name: Create the virtual Machine
      azure_rm_virtualmachine:
        name: rhel8
        resource_group: ansible-rhel-rg
        admin_username: jorge.arevalo
        admin_password: Passw0rd
        vm_size: Standar_A1_v2
        network_interfaces: ansible_rhel_nic
        image:
          offer: "RHEL"
          publisher: "RedHat"
          sku: "8"
          version: "latest"