---
- name: OS recognition from facts
  hosts: test
  vars_prompt:

    - name: my_username
      prompt: "What is your username?"
      private: no

    - name: my_password
      prompt: "What is your password?"

  tasks:
    - name: Printing facts or vars
      debug:
#        msg: "Hello  {{ rhsmuser }} {{ rhsmpoolid }} "
#        msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
         msg: System {{ inventory_hostname }} has {{ ansible_distribution }} OS with kernel {{ ansible_kernel }} from OS Family {{ ansible_os_family }}

    - name: Only If RedHat Family
  #    debug: 
  #       msg: System {{ inventory_hostname }} has {{ ansible_distribution }} OS with kernel {{ ansible_kernel }} from OS Family {{ ansible_os_family }} 
      shell: " systemctl list-units | grep -i network "
      register: out
#      debug: 
#        var:  out.stdout_lines
      when: ansible_os_family == 'RedHat'

    - debug: var=out.stdout_lines

    - name: Only If Solaris Family
  #    debug: 
  #       msg: System {{ inventory_hostname }} has {{ ansible_distribution }} OS with kernel {{ ansible_kernel }} from OS Family {{ ansible_os_family }} 
      shell: " svcs | grep -i network "
      register: out
      when: ansible_os_family == 'Solaris'

    - debug: var=out.stdout_lines

    - name: Input de variables
      debug:
          msg: 'Logging in as {{ my_username }} with {{ my_password }} '
...
