- name: Register as user with password  and autosubscribe to available content.
  hosts: all
  remote_user: root
# https://docs.ansible.com/ansible/latest/modules/redhat_subscription_module.html
  tasks: 
  
  - redhat_subscription:
      state: present
        username: "{{ rhsmuser }}"
        password: "{{ rhsmpasswd }}"
# bcb4c0565ba9982fac0b3d727bcb437e72b081b3
      # auto_attach: true
      # Pool ID:             8a85f99a710f3ae9017173aa6008424d
      pool_ids: 8a85f99a710f3ae9017173aa6008424d
