- hosts: nodes
- name: Register as user with password  and autosubscribe to available content.
  remote_user: root

  tasks: 
  - redhat_subscription:
      state: present
      username: jorge.arevalo@amauta.com.mx
      password: 51McPassw0rd
      auto_attach: true