- hosts: nodes
- name: Register as user with password  and auto-subscribe to available content.

  redhat_subscription:
    state: present
    username: jorge.arevalo@amauta.com.mx
    password: 51McPassw0rd
    auto_attach: true