---
- name: Editar sudoers
  hosts: 127.0.0.1

  tasks:
    - name: Replace Line in file 
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%ADMIN ALL='
        line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
#    - name: display multiple file contents
#      debug: var=item
#      with_file:
#        - "/etc/sudoers"
##        - "bar.txt"  # will be looked in files/ dir relative to play or in role
##        - "/path/to/biz.txt"
    - name: Ansible grep pattern basic example
      shell: "grep -i 'ADMIN' /etc/sudoers"
#      args:
#        chdir: "/etc/"
      register: grep_output
    
    - debug:
        var: grep_output.stdout_lines
...