---
- name: Three tier app
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

- name: Deploy haproxy
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: http
    package:
      name: httpie
      enablerepo: "epel,rhel-7-server-e4s-rpms,rhel-7-server-e4s-optional-rpms"
      state: latest
  - name: install HAProxy
    package:
      name: haproxy
      enablerepo: "epel,rhel-7-server-e4s-rpms,rhel-7-server-e4s-optional-rpms"
      state: latest
      
  - name: enable HAProxy
    service:
      name: haproxy
      state: started
  - name: configure haproxy
    template:
      src: ./tta-files/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: restart HAproxy
    service:
      name: haproxy
      state: restarted

...
