---
- name: Three tier app
#  hosts: all
#  gather_facts: false # remove later! speeds up testing
#  become: true

- name: Deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:

# https://docs.ansible.com/ansible/2.5/modules/blockinfile_module.html  
  - name: Add mappings to /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        {{ item.ip }} {{ item.name }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    with_items:
      - { name: appdb1, ip: 192.168.1.132 }
      - { name: app1, ip: 192.168.1.135 }
      - { name: app2, ip: 192.168.1.136 }
      - { name: frontend1, ip: 192.168.1.137 }
    
  - name: http
    package:
      name: httpie
      enablerepo: "epel,rhel-7-server-e4s-rpms,rhel-7-server-e4s-optional-rpms"
      state: latest
  - name: install HAProxy
    package:
      name: haproxy
      enablerepo: "epel,rhel-7-server-e4s-rpms,rhel-7-server-e4s-optional-rpms"
      state: latest
      
  - name: enable HAProxy
    service:
      name: haproxy
      state: started
  - name: configure haproxy
    template:
      src: ./tta-files/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: restart HAproxy
    service:
      name: haproxy
      state: restarted
      
  - name: Firewall Config
  - systemd: 
      name: firewalld
      state: started
      
  - firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
      
...
