---
- name: Three tier app
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
- name: Hello World Sample
  hosts: apps
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello  {{ rhsmuser }} {{ rhsmpoolid }} "

...
