---
- name: Three tier app
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

- name: Deploy apache
  hosts: apps
  gather_facts: false
  become: true
  tasks:
  
  - name: Install apache
    package:
      name: httpd
      state: latest
      
  - name: Enable apache at boot
    service:
      name: httpd
      enabled: yes
      
  - name: Start apache
    service:
      name: httpd
      state: started
      
...
