---
- name: OS recognition from facts
  hosts: all
  gather_facts: false

  tasks:
  
    - name: ROLLBACK 1
    win_service:
      name: wuauserv
      start_mode: enabled        
      state: started 
  - name: ROLLBACK 2
    ##     "msg": "win_firewall requires Windows Management Framework 5 or higher.",
    win_firewall:
      state: enabled
      profiles:
      - Domain
      - Private
      - Public

    
  - name: ping test
    win_ping:

  - name: Touch a file (creates if not present, updates modification time if present)
    win_file:
      path: C:\foo.conf
      state: touch

  - name: Remove a file, if present
    win_file:
      path: C:\foo.conf
      state: absent

  - name: Change the hostname 
    win_hostname:
      name: "VLA000{{ HOSTNAMENUMBER }}r01"
    register: res

  - name: Reboot
    win_reboot:
    when: res.reboot_required
# tarda 4min después de llegar al Windows Login screen en VMWARE

  - name: Install hotfix without validating the KB and Identifier
# ya no funciona...
    win_hotfix:
      source: C:\Users\cajero\March, 2017 Security Only Quality Update for Windows 7 (KB4012212)\X86-all-windows6.1-kb4012212-x86_6bb04d3971bb58ae4bac44219e7169812914df3f.msu
      #source: "C:\\Users\\cajero\\March,\ 2017\ Security\ Only\ Quality\ Update\ for\ Windows\ 7\ (KB4012212)\\X86-all-windows6.1-kb4012212-x86_6bb04d3971bb58ae4bac44219e7169812914df3f.msu"
      state: present
    register: hotfix_install

  - win_reboot:
    when: hotfix_install.reboot_required
  
  - name: Disable firewall for Domain, Public and Private profiles
    ##     "msg": "win_firewall requires Windows Management Framework 5 or higher.",
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall
# Get-NetFirewallProfile -Profile Domain, Public, Private | Select-Object Name, Enabled
    
  - name: Set service startup mode to disabled and ensure it is stopped
    win_service:
      name: wuauserv
      start_mode: disabled        
      state: stopped   

#  - name: Copy files
#    win_copy:
#      src: /shared/Disco-C-Caja.zip
#      dest: C:\Users\cajero\
  
  - name: Recursively decompress GZ files
    win_unzip:
      src: "C:\\Users\\cajero\\Downloads\\Disco\ C\ Caja.zip"
      dest: C:\Users\cajero
      
  - name: Recursively decompress GZ files
    win_unzip:
      src: "C:\\Users\\cajero\\Downloads\\Disco\ C\ Server.zip"
      dest: C:\Users\cajero


### TEST ONLY
  - name: Set service startup mode to disabled and ensure it is stopped
    win_service:
      name: "{{ item }}"
      start_mode: disabled        
      state: stopped 
    loop: 
      - msdtc
      - sqlserveragent

  - name: Copy a folder recursively where the source is on the remote host
  #     "exception": "Excepción al llamar a \"Open\" con los argumentos \"4\": \"The process cannot access the file 'C:\\MSSQLDB\\Posbdat.mdf' because it is being used by another process.\"\r\nEn línea: 340 Carácter: 13\r\n+             $fp = [System.IO.File]::Open($path, [System.IO.Filemode]::Open, [Sys ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : IOException\r\n\r\nScriptStackTrace:\r\nen Get-FileChecksum, <sin archivo>: línea 340\r\nen Copy-File, <sin archivo>: línea 58\r\nen Copy-Folder, <sin archivo>: línea 125\r\nen <ScriptBlock>, <sin archivo>: línea 328\r\n",
    win_copy:
      src: C:\Users\cajero\Disco C Server\{{ item }}
      dest: C:\
      remote_src: yes
    loop:
      - ArchivosEntrada
      - MSSQLDB
      - PathFact
      - PathFE
      - Pos
      - PosADV
      - Skins 

############################
# INSTALACION DE PAQUETES
# 36.- carpeta instalador ARSPOS y ejecutaremos el setup.contraseña: 5650009. usuario predefinido, instalación personalizada. En la ventana Seleccionar componentes seleccionaremos solamente las opciones Frontend, Backoffice y Componentes; Corporativo y MSDE SP4 no deben estar marcadas. 
# carpeta llamada MSDE SP4, y ejecutaremos el setup que está dentro de la carpeta. Al momento de ejecutar el programa, Windows mostrará una advertencia que indica Este programa tiene problemas de compatibilidad conocidos. Aparecerá un botón de ejecutar programa, hay que dar clic dos veces en esa opción para que el programa se instale adecuadamente, ya que la ventana se abre dos veces.
# 38.- REBOOT carpeta PosADV dentro de la carpeta raíz del disco C. Dentro de esa carpeta, hay un archivo llamado Setup_DBAMgr2k. Es preciso que se instale a través del Wizard, con todas las preferencias default. Al finalizar la instalación, el sistema requerirá un reinicio.
# Servicios : El primero de ellos es configurar el servicio coordinador de transacciones distribuidas cambiándolo a Automático y después iniciarlo. Después, el servicio SQLSERVERAGENT debe ser cambiado a Automático y deber ser iniciado. Esto se logra dando clic derecho a "Manual" y luego en propiedades.
# ejecutar DbaMGR2k y cambiar el nombre de la db a la que se va conectar (nuevo hostname)
# 
############################

  - name: Set service startup mode to disabled and ensure it is stopped
    win_service:
      name: "{{ item }}"
      start_mode: auto        
      state: started 
    loop: 
      - msdtc
      - sqlserveragent

############################
# 43.- ejecutar scripts carpeta PosADV  en sql para llenar la info en la base
# 44.- Hacer el mismo procedimiento con el archivo sql Reindex
# 44.- Hacer el mismo procedimiento con el archivo sql Compactar DBs. 
# 45.- Hacer el mismo procedimiento con el archivo sql "cambiar nombre del server" (tienda) antes de ejecutar el aql
# 46.- Parámetros de Sucursal. modificar info de la sucursal basada en el excel.
# 47.- El último script que vamos a correr es script de facturación. En la parte de posbdat y posfdat se debe de sustituir TNY por el prefijo de la tienda correspondiente en el EXCEL
# Install:
# https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15 
# https://go.microsoft.com/fwlink/?linkid=2142257
# Install:
# https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15  
# https://go.microsoft.com/fwlink/?linkid=2142257  
#   
#   - name: "SQL Script Execution"
#       win_command: sqlcmd -S "VLA000{{ HOSTNAMENUMBER }}r01" -i "C:\\PosADV\\Scripts\\Cambia el nombre de servidor.sql"
#       register: sqlcmd_out 
# 
## sqlcmd NO acepta conexiones a SQL 2000  
#############################

############################
#48.- ejecutar el app generador de licencia 
############################

  - name: Recursively decompress GZ files
    win_unzip:
      src: C:\PosADV\Reemplazar version.zip
      dest: C:\PosADV\

  - name: Copy a folder recursively where the source is on the remote host
    win_copy:
      src: C:\PosADV\Reemplazar version\AdvancedSP\Frontend
      dest: C:\Program Files\AdvancedSP
      remote_src: yes

  - name: Copy a folder recursively where the source is on the remote host
### RARO... de otra forma no funciona...    
    win_copy:
      src: C:\PosADV\Reemplazar version\System32\{{ item }}
      dest: C:\Windows\System32\
      remote_src: yes
      force: yes
    loop:
      - ROS800.dll
      - RosArsl.dll
      - RosDM.dll
      - RosExits.dll
      - RosF.dll
      - RosFacturacion.dll
      - RosSkins.DLL


  - name: Run script
    win_command: cmd.exe C:\Program Files\AdvancedSP\Frontend\Registrar.bat
    become: yes
    become_method: runas
    become_user: SYSTEM


  - name: Remove directory structure
    win_file:
      path: C:\Program Files\AdvancedSP\Backend
      state: absent

  - name: Copy a folder recursively where the source is on the remote host
    win_copy:
      src: C:\PosADV\Reemplazar version\AdvancedSP\Backend
      dest: C:\Program files\AdvancedSP
      remote_src: yes

  - name: Run script
    win_command: cmd.exe C:\Program files\AdvancedSP\Backend\Registrar BO.bat
    become: yes
    become_method: runas
    become_user: SYSTEM


  - name: Run script
    win_command: cmd.exe C:\PosADV\Reemplazar version\Frontend.reg
    become: yes
    become_method: runas
    become_user: SYSTEM

############################# ocupa interaccion humana.
# 58.- se ocupa impresora conectada. 
# 59.- ejecutar aplicativo para establecer configuracion
# 69.- ejecutar aplicativo para establecer configuracion
# 77.-  REBOOT instalar proxy con licencia (textO)
############################


############################ Para CAJA 2 TBD      
#  - name: Copy a folder recursively where the source is on the remote host
#    win_copy:
#      src: C:\Users\cajero\Disco C Caja\{{ item }}
#      dest: C:\
#      remote_src: yes
#    loop:
#      - MSSQLDB
#      - PathFact
#      - PathFE
#      - Pos
#      - PosADV
#      - Skins 
...
