---
- name: OS recognition from facts
  hosts: all
  gather_facts: false

  tasks:
  - name: ping test
    win_ping:

  - name: Touch a file (creates if not present, updates modification time if present)
    win_file:
      path: C:\foo.conf
      state: touch

  - name: Remove a file, if present
    win_file:
      path: C:\foo.conf
      state: absent

  - name: Change the hostname 
    win_hostname:
      name: "VLA000{{ HOSTNAMENUMBER }}r01"
    register: res

  - name: Reboot
    win_reboot:
    when: res.reboot_required
# tarda 4min después de llegar al Windows Login screen en VMWARE

  - name: Install hotfix without validating the KB and Identifier
    win_hotfix:
      source: C:\Users\cajero\March, 2017 Security Only Quality Update for Windows 7 (KB4012212)\X86-all-windows6.1-kb4012212-x86_6bb04d3971bb58ae4bac44219e7169812914df3f.msu
      state: present
    register: hotfix_install

  - win_reboot:
    when: hotfix_install.reboot_required
  
  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall
    
  - name: Set service startup mode to disabled and ensure it is stopped
    win_service:
      name: wuauserv
      start_mode: disabled        
      state: stopped   

#  - name: Copy files
#    win_copy:
#      src: /shared/Disco-C-Caja.zip
#      dest: C:\Users\cajero\
  
  - name: Recursively decompress GZ files
    win_unzip:
      src: "C:\\Users\\cajero\\Downloads\\Disco\ C\ Caja.zip"
      dest: C:\Users\cajero
      
  - name: Recursively decompress GZ files
    win_unzip:
      src: "C:\\Users\\cajero\\Downloads\\Disco\ C\ Server.zip"
      dest: C:\Users\cajero

  - name: Copy a folder recursively where the source is on the remote host
    win_copy:
      src: C:\Users\cajero\Disco C Server\{{ item }}
      dest: C:\
      remote_src: yes
    loop:
      - ArchivosEntrada
      - MSSQLDB
      - PathFact
      - PathFE
      - Pos
      - PosADV
      - Skins 

############################
# INSTALACION DE PAQUETES
############################

  - name: Set service startup mode to disabled and ensure it is stopped
    win_service:
      name: "{{ item }}"
      start_mode: auto        
      state: started 
    loop: 
      - msdtc
      - sqlserveragent

############################
# 43.- ejecutar scripts carpeta PosADV  en sql para llenar la info en la base
# 44.- Hacer el mismo procedimiento con el archivo sql Reindex
# 44.- Hacer el mismo procedimiento con el archivo sql Compactar DBs. 
# 45.- Hacer el mismo procedimiento con el archivo sql "cambiar nombre del server" (tienda) antes de ejecutar el aql
# 46.- Parámetros de Sucursal. modificar info de la sucursal basada en el excel.
# 47.- El último script que vamos a correr es script de facturación. En la parte de posbdat y posfdat se debe de sustituir TNY por el prefijo de la tienda correspondiente en el EXCEL
# Install:
# https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15 
# https://go.microsoft.com/fwlink/?linkid=2142257
# Install:
# https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15  
# https://go.microsoft.com/fwlink/?linkid=2142257  
#   
#   - name: "SQL Script Execution"
#       win_command: sqlcmd -S "VLA000{{ HOSTNAMENUMBER }}r01" -i "C:\\PosADV\\Scripts\\Cambia el nombre de servidor.sql"
#       register: sqlcmd_out 
# 
## sqlcmd NO acepta conexiones a SQL 2000  
############################

  - name: Recursively decompress GZ files
    win_unzip:
      src: C:\PosADV\Reemplazar version.zip
      dest: C:\PosADV\

  - name: Copy a folder recursively where the source is on the remote host
    win_copy:
      src: C:\PosADV\Reemplazar version\AdvancedSP\Frontend
      dest: C:\Program Files\AdvancedSP
      remote_src: yes

  - name: Copy a folder recursively where the source is on the remote host
    win_copy:
      src: C:\PosADV\Reemplazar version\System32
      dest: C:\Windows
      remote_src: yes

C:\Archivos de programa\AdvancedSP\Frontend\Registrar.bat

  - name: Copy a folder recursively where the source is on the remote host
    win_copy:
      src: 
      dest: 
      remote_src: yes













############################ Para CAJA 2 TBD      
#  - name: Copy a folder recursively where the source is on the remote host
#    win_copy:
#      src: C:\Users\cajero\Disco C Caja\{{ item }}
#      dest: C:\
#      remote_src: yes
#    loop:
#      - MSSQLDB
#      - PathFact
#      - PathFE
#      - Pos
#      - PosADV
#      - Skins 
...
