---
- name: OS recognition from facts
  hosts: all

  tasks:
  - name: ping test
    win_ping:

  - name: Touch a file (creates if not present, updates modification time if present)
    win_file:
      path: C:\foo.conf
      state: touch

  - name: Remove a file, if present
    win_file:
      path: C:\foo.conf
      state: absent
...
