---
- hosts: frontends
  remote_user: root
  tasks: 
  - systemd: state=started name=firewalld
  - firewalld:
      port: 80/tcp
      permanent: true
      immediate: yes
      state: disabled
  # - firewalld:
      # port: 443/tcp
      # permanent: true
      # immediate: yes
      # state: disabled
  - firewalld:
      port: 5647/tcp
      permanent: true
      immediate: yes
      state: disabled
  - firewalld:
      port: 8000/tcp
      permanent: true
      immediate: yes
      state: disabled
  - firewalld:
      port: 8140/tcp
      permanent: true
      immediate: yes
      state: disabled
  - firewalld:
      port: 53/tcp
      permanent: true
      immediate: yes
      state: disabled
  - firewalld:
      port: 53/udp
      permanent: true
      immediate: yes
      state: disabled
  - firewalld:
      port: 67/udp
      permanent: true
      immediate: yes
      state: disabled
  - firewalld:
      port: 68/udp
      permanent: true
      immediate: yes
      state: disabled
#################################################################################################################### mixed
  - firewalld:
      service: https
      permanent: yes
      immediate: yes
      state: disabled

  - firewalld:
      port: 8081/tcp
      permanent: yes
      immediate: yes
      state: disabled
  
  - firewalld:
      port: 161-162/udp
      permanent: yes
      immediate: yes
      state: disabled
  
  - firewalld:
      zone: dmz
      service: http
      permanent: yes
      immediate: yes
      state: disabled
  
  - firewalld:
      rich_rule: rule service name="ftp" audit limit value="1/m" accept
      permanent: yes
      immediate: yes
      state: disabled
  
  - firewalld:
      source: 192.168.1.0/24
      zone: internal
      state: disabled
  
  - firewalld:
      zone: trusted
      interface: enp0s3
      permanent: yes
      immediate: yes
      state: disabled
  
  - firewalld:
      masquerade: yes
      state: disabled
      permanent: yes
      immediate: yes
      zone: dmz
  
  - firewalld:
      zone: custom
      state: present
      permanent: yes
      immediate: yes
  
  - firewalld:
      zone: drop
      state: present
      permanent: yes
      immediate: yes
      icmp_block_inversion: yes
  
  - firewalld:
      zone: drop
      state: present
      permanent: yes
      immediate: yes
      icmp_block: echo-request
  
  # - name: Redirect port 443 to 8443 with Rich Rule
    # firewalld:
      # rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
      # zone: public
      # permanent: yes
      # immediate: yes
      # state: disabled


...