---
- hosts: sat63
  remote_user: root
  tasks: 
  # Asignar hostname
  # Apagar o agregar puertos de fw
  - redhat_subscription:
        state: present
        username: "{{ rhsmuser }}"
        password: "{{ rhsmpasswd }}"
  - name: (='_'=) Gestionando repositorios (-O_O-).
    shell: |
            subscription-manager attach --pool={{rhsmpoolid}}
            subscription-manager repos --disable=*
            subscription-manager repos --enable={{ repobase }} --enable={{ reposcl }} --enable={{ reposat }}
    when:  ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  - name: /^_^\ Actualizando el sistema (*_*).
    yum:
            name: '*'
            state: latest
  - name: (='_'=) Instalando Satellite (+_+).
    yum:
            name: satellite
            state: present
  - name: (".") Ejecutando instalador de Satellite (^-^)
    shell: |
          satellite-installer --scenario satellite --foreman-initial-organization ""{{ orgsat }}"" --foreman-initial-location ""{{ locsat }}"" --foreman-admin-password "{{ adminpasswd }}" --foreman-proxy-puppetca true --foreman-proxy-tftp true --enable-foreman-plugin-discovery
####  - name: (`.') Configurando ambiente de hammer (°-°)
####    file:
####            path: "~/.hammer"
####            state: "directory"
####            mode: "0755"
####  - name: ='.'= Copiando archivo de configuración ('=')
####    template:
####            src: "hammer_config_yml.j2"
####            dest: "~/.hammer/cli_config.yml"
####            mode: 600
...
